{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plot-reel.fullname" . }}-secret
  labels:
    {{- include "plot-reel.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.keyBase64 }}
  key: {{ .Values.secrets.keyBase64 }}
  {{- end }}
  {{- if .Values.secrets.userscsvBase64 }}
  users.csv: {{ .Values.secrets.userscsvBase64 }}
  {{- end }}
{{- end }}